name: Ping me

on:
  schedule:
    - cron: '*/29 * * * 1-5'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
      - name: Check the site
        id: hello
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://deploy-listener-bot.herokuapp.com/probot"
          expected-statuses: "200,301"
