name: Keep my bot awake during workdays

on:
  schedule:
    - cron: '*/20 * * * 1-5'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
      - name: Ping Heroku free
        id: ping-ping
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://deploy-listener-bot.herokuapp.com/probot"
          expected-statuses: "200,301"